---
# Fabric vars
---
fabric_name: datacenter_fabric

# Set Design Type to L2ls
design:
  type: l2ls

# Spine Switches
l3spine:
  defaults:
    platform: ceos
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 1.1.1.0/24
    mlag_peer_ipv4_pool: 192.0.0.0/24
    mlag_peer_l3_ipv4_pool: 192.1.1.0/24
    virtual_router_mac_address: aa:aa:bb:bb:cc:cc
    mlag_interfaces: [Ethernet1, Ethernet6]
  node_groups:
    SPINES:
      nodes:
        spine1:
          id: 1
          mgmt_ip: 192.168.0.10/24
        spine2:
          id: 2
          mgmt_ip: 192.168.0.11/24

# IDF - Leaf Switches
leaf:
  defaults:
    platform: ceos
    mlag_peer_ipv4_pool: 192.0.0.0/24
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    uplink_switches: [spine1, spine2]
    uplink_interfaces: [Ethernet2, Ethernet3]
    mlag_interfaces: [Ethernet1, Ethernet6]
  node_groups:
    RACK1:
      mlag: true
      filter:
        tags: [ 10 ]
      nodes:
        leaf1:
          id: 3
          mgmt_ip: 192.168.0.12/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
        leaf2:
          id: 4
          mgmt_ip: 192.168.0.13/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
    RACK2:
      mlag: true
      filter:
        tags: [ 10 ]
      nodes:
        leaf3:
          id: 5
          mgmt_ip: 192.168.0.14/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
        leaf4:
          id: 6
          mgmt_ip: 192.168.0.15/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5]

# IDF - Host Switches
    HOST1:
      mlag: false
      nodes:
        host1:
          id: 7
          mgmt_ip: 192.168.0.16/24
          uplink_interfaces: [Ethernet1, Ethernet2]
          uplink_switches: [leaf1, leaf2]
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
          structured_config:
            vlan_interfaces:
              Vlan10:
                description: In-band Management
                ip_address: 10.10.10.101/24
            static_routes:
              - destination_address_prefix: 10.0.0.0/8
                gateway: 10.10.10.1
              - destination_address_prefix: 0.0.0.0/0
                gateway: 192.168.0.1

    HOST2:
      mlag: false
      nodes:
        host2:
          id: 8
          mgmt_ip: 192.168.0.17/24
          uplink_interfaces: [Ethernet1, Ethernet2]
          uplink_switches: [leaf3, leaf4]
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
          structured_config:
            vlan_interfaces:
              Vlan20:
                description: In-band Management
                ip_address: 10.20.20.101/24
            static_routes:
              - destination_address_prefix: 10.0.0.0/8
                gateway: 10.20.20.1
              - destination_address_prefix: 0.0.0.0/0
                gateway: 192.168.0.1

